import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";

// Fonts not used in body yet, you can add them to className if needed

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `window.ENV = { API_URL: "${process.env.RUNTIME_API_URL || process.env.NEXT_PUBLIC_API_URL || ''}" };`,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
